### ISSUE TITLE
Vertical tabs

### ISSUE THREAD

**Issue by cseickel** [noib3/cokeline.nvim#4]
I've been thinking about making a plugin that shows open buffers in a sidebar instead of in the tab bar. The reason for this is I usually have more buffers open than can fit in the tab bar, and to me it that ruins the purpose of showing buffers as tabs.

This is my favorite implementation of a buffer based tab line, and I think it would be a good idea to just add vertical tabs as a feature to this project rather than starting from scratch. The question is, are you interested in adding this feature to the project? I would be willing to do the work and put in a PR if you think it is something you would want to have here.

**Comment by noib3** [comment]
If the reason for having a vertical bufferline is to always show all the listed buffers, no matter of many of them there are, then I think a better solution is what I described in the third bullet point of the TODOs section in the main README.

I'm not completely opposed to the idea of a vertical bufferline though. I'm not sure how would look or how much of the already existing code could be reused. Personally I wouldn't use this feature, but I'll leave this issue open in case someone else wants to chime in.

**Comment by cseickel** [comment]
Squashing the tabs would certainly help, up to a point. I agree it is definitely a good idea to do that work as well. It would be interesting to see if that is enough for my day to day usage. Have you started work on that?

**Comment by noib3** [comment]
> Have you started work on that?

I haven't, but simply rendering all the buffers giving their lines *1/n* the available width would be really easy, say 15 minutes of work. The reason I haven't implemented this yet is because I'm unsure how to cutoff the text of the buffers.

To give an example, let's say we need to cutoff a line whose full text is
```
1: areallyreallyreallylongname.lua x
------------------------------------
```
to just 15 characters. A possible implementation would be to just take the first 14 characters, append an ellipses and cut the rest, so that the text becomes
```
1: areallyreal…
...............
```

But we can do better. We'd probably want to keep the close button visible as the line shrinks, and the filename should get cutoff from the left, so that that line gets rendered as
```
1: …gname.lua x
...............
```

To do this we'd have to add at least 2 properties to every component:

  1. a number specifying a sort of priority, so that components with higher priority are cut off last;
  2. the direction in which a component should be cutoff.

Implementing 2. is trivial, implementing 1. definitely isn't.

**Comment by cseickel** [comment]
I have ideas on that, I'll post them later. 

I think it would be best to open a separate issue on for discussion on how to shorten/collapse components when there is not enough space. It's really a universal issue that could come apply with or without implementing vertical tabs or a force fit all tabs strategy.

**Comment by cseickel** [comment]
If no one else is interested in this, feel free to close it. I now believe that a tree plugin is a more natural place to implement this functionality.

**Comment by pencilcheck** [comment]
wonder what's the follow up on this, would be nice to know if there exist something that can do that. not liking buffers is acting like tabs and then opening tabs the buffer line disappear as well. want buffer to be on the left stacking on top of the file tree similar to vscode.

**Comment by cseickel** [comment]
@pencilcheck This issue was actually the reason why I created Neo-tree, it has the ability to show open buffers in a tree as a sidebar: https://github.com/nvim-neo-tree/neo-tree.nvim#buffers
